v02.00.04: housekeeping
* Manifest
  - don't require a 'signature' level permission

* README
  - maximum supported version: Android 5.1 (API 22)

* gradle
  - targetSdk = 22

references:
===========

* BROADCAST_SMS has been a 'signature' level permission since (at least) Android 1.6 Donut (API 4)
  - https://android.googlesource.com/platform/frameworks/base/+/donut-release/core/res/AndroidManifest.xml#951
      <permission android:name="android.permission.BROADCAST_SMS" android:protectionLevel="signature" />

* SMS_RECEIVED and DATA_SMS_RECEIVED were initially unprotected
  - https://android.googlesource.com/platform/packages/services/Telephony/+/kitkat-release/AndroidManifest.xml
  - https://android.googlesource.com/platform/packages/services/Telephony/+/lollipop-release/AndroidManifest.xml

* SMS_RECEIVED and DATA_SMS_RECEIVED became protected in Android 6.0 Marshmallow (API 23)
  - https://android.googlesource.com/platform/packages/services/Telephony/+/marshmallow-release/AndroidManifest.xml#42
      <protected-broadcast android:name="android.intent.action.DATA_SMS_RECEIVED" />
      <protected-broadcast android:name="android.provider.Telephony.SMS_RECEIVED" />
  - attempts to broadcast result in:
      SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.DATA_SMS_RECEIVED
      SecurityException: Permission Denial: not allowed to send broadcast android.provider.Telephony.SMS_RECEIVED